docs(images): update path of images
AlaskaAirlines/auro-banner pull request #60
Opened 2024-05-02 20:41 UTC by braven112

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #59 

## Summary:

Updated all the image references.

## Type of change:

Please delete options that are not relevant.

- [x] Other (Demo image url update)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-05-03 19:30 UTC, jordanjones243 reviewed
When running a build, it shows that there were changes to the files, but none are shown. Otherwise, the changes look good and can be merged once this is investigated.

2024-05-08 20:18 UTC, jordanjones243 submitted a review, later dismissed

2024-05-13 16:18 UTC, jason-capsule42 requested changes

2024-05-13 16:18 UTC, jason-capsule42 commented on demo/api.md
Shouldn't all the changes here and in index.md be in the docs/partials/ template files?

2024-05-13 21:01 UTC, jordanjones243 commented on demo/api.md
I don't think so, I am not even sure why it shows so much changed. As far as I know, no content was changed besides the image links.

2024-05-13 21:46 UTC, jason-capsule42 approved these changes

2024-05-13 21:46 UTC, merged

2024-05-13 21:48 UTC, blackfalcon commented
:tada: This PR is included in version 2.0.7 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-banner/v/2.0.7)
- [GitHub release](https://github.com/AlaskaAirlines/auro-banner/releases/tag/v2.0.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: