Update color tokens
AlaskaAirlines/auro-banner pull request #61
Opened 2024-06-06 19:24 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #57 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Update all dependencies, most importantly the design tokens
* Refactor color tokens by isolating the color tokens and creating tier 3 tokens for repeatable rules

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

## Verification

- [ ] Tier 3 tokens are appropriately named
- [ ] Tier 3 tokens are pointing to correct tier 2 tokens

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-07-01 16:26 UTC, jason-capsule42 requested changes

2024-07-01 16:26 UTC, jason-capsule42 commented on demo/api.md
> +  --ds-auro-banner-text-color: var(--ds-color-text-primary-default, $ds-color-text-primary-default);
Alphabetize

2024-07-01 16:26 UTC, jason-capsule42 commented on demo/api.md
> +  --ds-auro-banner-icon-background-color: var(--ds-color-icon-tertiary-default, $ds-color-icon-tertiary-default);
```suggestion
  --ds-auro-banner-icon-container-color: var(--ds-color-icon-tertiary-default, $ds-color-icon-tertiary-default);
```

Why are we using a icon token for a background rule?

2024-07-01 16:26 UTC, jason-capsule42 commented on demo/api.md
> +  --ds-auro-banner-wrapper-background-color: var(--ds-color-brand-midnight-400, $ds-color-brand-midnight-400);
We have to figure out how to extract the Tier 1 brand color out of here so that it works with the Hawaiian theme, etc.

2024-07-08 23:24 UTC, blackfalcon requested changes

2024-07-08 23:24 UTC, blackfalcon commented on src/tokens.scss
> +  --ds-auro-banner-wrapper-border-color: var(--ds-color-border-primary-default, $ds-color-border-primary-default);
```suggestion
// Import Auro tokens
@import "./../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SCSSVariables";

:host {
  --ds-auro-banner-text-color: var(--ds-color-text-primary-default, #{$ds-color-text-primary-default});
  --ds-auro-banner-disclaimer-text-color: var(--ds-color-text-secondary-default, #{$ds-color-text-secondary-default});
  --ds-auro-banner-title-text-color: var(--ds-color-text-emphasis-default, #{$ds-color-text-emphasis-default});
  --ds-auro-banner-icon-background-color: var(--ds-color-icon-tertiary-default, #{$ds-color-icon-tertiary-default});
  --ds-auro-banner-wrapper-background-color: var(--ds-color-brand-midnight-400, #{$ds-color-brand-midnight-400});
  --ds-auro-banner-wrapper-border-color: var(--ds-color-border-primary-default, #{$ds-color-border-primary-default});
```

Also, `$ds-color-icon-tertiary-default` is ** not** a token?

2024-07-08 23:27 UTC, blackfalcon commented
I am seeing this in a few repos where there are tier 3 tokens being defined, when using this syntax pattern, Sass Interpolation is needed to process the Sass var into a value. 

```
--ds-auro-banner-wrapper-border-color: var(--ds-color-border-primary-default, #[$ds-color-border-primary-default});
```

2024-07-09 02:42 UTC, jason-capsule42 requested changes
I made several updates based on the previous review comments in an attempt to get this done.

However, there is one issue that still needs attention. All the banner images are misaligned on the bottom of the banner. This needs to be fixed before this can release to beta.

2024-07-09 17:17 UTC, jordanjones243 commented
> I made several updates based on the previous review comments in an attempt to get this done.
> 
> However, there is one issue that still needs attention. All the banner images are misaligned on the bottom of the banner. This needs to be fixed before this can release to beta.

The issue that is seen has been verified to appear in the `main` branch as well, meaning the work from this repo can proceed.

2024-07-09 21:21 UTC, jason-capsule42 approved these changes

2024-07-09 21:39 UTC, merged

2024-07-09 21:41 UTC, blackfalcon commented
:tada: This PR is included in version 2.1.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-banner/v/2.1.0-beta.1)
- [GitHub release](https://github.com/AlaskaAirlines/auro-banner/releases/tag/v2.1.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: